#!/usr/bin/env python3
"""CLI wrapper for create-weekly-note."""
import argparse
import sys


def main():
    parser = argparse.ArgumentParser(prog="create-weekly-note")
    parser.add_argument("--template-path", required=True)
    parser.add_argument("--target-dir", required=True)
    parser.add_argument("--date", default=None, help="Optional date YYYY-MM-DD")
    args = parser.parse_args()

    from doppiozero.create_weekly_note import create_weekly_note

    create_weekly_note(args.template_path, args.target_dir, date=args.date)


if __name__ == "__main__":
    main()
