#!/usr/bin/env python3
"""CLI wrapper for prepare-commit (generate commit message using LLM prompt)."""
import argparse
import sys


def main():
    parser = argparse.ArgumentParser(prog="prepare-commit")
    parser.add_argument("--commit-message-prompt-path", required=True)
    parser.add_argument("--llm-model", default=None)
    args = parser.parse_args()

    from doppiozero.prepare_commit import prepare_commit

    msg = prepare_commit(args.commit_message_prompt_path, llm_model=args.llm_model)
    print(msg)


if __name__ == "__main__":
    main()
