#!/usr/bin/env python3
"""CLI wrapper for select-folder."""
import argparse
import sys
import os


def select_folder(target_dir: str) -> str:
    folders = [f.path for f in os.scandir(target_dir) if f.is_dir()]
    if not folders:
        return ""
    folders.sort(key=lambda x: os.path.getmtime(x), reverse=True)
    return folders[0]


def main():
    parser = argparse.ArgumentParser(prog="select-folder")
    parser.add_argument("--target-dir", default=".")
    args = parser.parse_args()

    folder = select_folder(args.target_dir)
    if folder:
        print(folder)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
