#!/usr/bin/env python3
"""CLI wrapper for select-folder."""
import argparse
import sys


def main():
    parser = argparse.ArgumentParser(prog="select-folder")
    parser.add_argument("--target-dir", default=".")
    args = parser.parse_args()

    from doppiozero.select_folder import select_folder

    folder = select_folder(args.target_dir)
    if folder:
        print(folder)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
